### ISSUE TITLE
can not find module '../config.js'

### ISSUE THREAD

**Issue by pramodwagh** [jdwong415/hotel-booking#62]
module.js:487
    throw err;
    ^

Error: Cannot find module '../config.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Pramod\Videos\hotelbook\hotel-booking-master
\controllers\api-yelp.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

how to solve this error

**Comment by sandaruwan9495** [comment]
This can be resolved by creating a config.json file in the root directory and add the following json object.

> `{
    "clientId": "123456789",
    "clientSecret" : "123456789"
  }`
then require this file in the api-yelp.js file in controllers folder instead of line number 4 `require("../config.js")`.

**Comment by cookiesikeri** [comment]
{ "clientId": "123456789", "clientSecret" : "123456789" }
then require this file in the api-yelp.js file in controllers folder instead of line number 4 require("../config.js").
it  should work

**Comment by thilak46kumar** [comment]
> This can be resolved by creating a config.json file in the root directory and add the following json object.
> 
> > `{     "clientId": "123456789",     "clientSecret" : "123456789"   }`
> > then require this file in the api-yelp.js file in controllers folder instead of line number 4 `require("../config.js")`
still  i am getting error like ==== cannot find module ..config.js
